// Code generated by protoc-gen-go. DO NOT EDIT.
// source: add.proto

package add

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdderRequest struct {
	FirstNum             int32    `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	SecondNum            int32    `protobuf:"varint,2,opt,name=secondNum,proto3" json:"secondNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdderRequest) Reset()         { *m = AdderRequest{} }
func (m *AdderRequest) String() string { return proto.CompactTextString(m) }
func (*AdderRequest) ProtoMessage()    {}
func (*AdderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_077cd88a1973142f, []int{0}
}

func (m *AdderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdderRequest.Unmarshal(m, b)
}
func (m *AdderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdderRequest.Marshal(b, m, deterministic)
}
func (m *AdderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdderRequest.Merge(m, src)
}
func (m *AdderRequest) XXX_Size() int {
	return xxx_messageInfo_AdderRequest.Size(m)
}
func (m *AdderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdderRequest proto.InternalMessageInfo

func (m *AdderRequest) GetFirstNum() int32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *AdderRequest) GetSecondNum() int32 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type AdderResponse struct {
	AddResult            int32    `protobuf:"varint,1,opt,name=addResult,proto3" json:"addResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdderResponse) Reset()         { *m = AdderResponse{} }
func (m *AdderResponse) String() string { return proto.CompactTextString(m) }
func (*AdderResponse) ProtoMessage()    {}
func (*AdderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_077cd88a1973142f, []int{1}
}

func (m *AdderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdderResponse.Unmarshal(m, b)
}
func (m *AdderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdderResponse.Marshal(b, m, deterministic)
}
func (m *AdderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdderResponse.Merge(m, src)
}
func (m *AdderResponse) XXX_Size() int {
	return xxx_messageInfo_AdderResponse.Size(m)
}
func (m *AdderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdderResponse proto.InternalMessageInfo

func (m *AdderResponse) GetAddResult() int32 {
	if m != nil {
		return m.AddResult
	}
	return 0
}

func init() {
	proto.RegisterType((*AdderRequest)(nil), "AdderRequest")
	proto.RegisterType((*AdderResponse)(nil), "AdderResponse")
}

func init() { proto.RegisterFile("add.proto", fileDescriptor_077cd88a1973142f) }

var fileDescriptor_077cd88a1973142f = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4c, 0x49, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xf2, 0xe0, 0xe2, 0x71, 0x4c, 0x49, 0x49, 0x2d, 0x0a, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x48, 0xcb, 0x2c, 0x2a, 0x2e, 0xf1, 0x2b,
	0xcd, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x8b, 0x53,
	0x93, 0xf3, 0xf3, 0x52, 0x40, 0x92, 0x4c, 0x60, 0x49, 0x84, 0x80, 0x92, 0x2e, 0x17, 0x2f, 0xd4,
	0xa4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x90, 0xf2, 0xc4, 0x94, 0x94, 0xa0, 0xd4, 0xe2, 0xd2,
	0x9c, 0x12, 0xa8, 0x59, 0x08, 0x01, 0x23, 0x7d, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x0d, 0x2e,
	0x56, 0xb0, 0x2e, 0x21, 0x5e, 0x3d, 0x64, 0x77, 0x48, 0xf1, 0xe9, 0xa1, 0x18, 0xa6, 0xc4, 0x90,
	0xc4, 0x06, 0x76, 0xb0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xb7, 0x8d, 0xd7, 0xbd, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddClient is the client API for Add service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddClient interface {
	Adder(ctx context.Context, in *AdderRequest, opts ...grpc.CallOption) (*AdderResponse, error)
}

type addClient struct {
	cc *grpc.ClientConn
}

func NewAddClient(cc *grpc.ClientConn) AddClient {
	return &addClient{cc}
}

func (c *addClient) Adder(ctx context.Context, in *AdderRequest, opts ...grpc.CallOption) (*AdderResponse, error) {
	out := new(AdderResponse)
	err := c.cc.Invoke(ctx, "/Add/Adder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServer is the server API for Add service.
type AddServer interface {
	Adder(context.Context, *AdderRequest) (*AdderResponse, error)
}

// UnimplementedAddServer can be embedded to have forward compatible implementations.
type UnimplementedAddServer struct {
}

func (*UnimplementedAddServer) Adder(ctx context.Context, req *AdderRequest) (*AdderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Adder not implemented")
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_Adder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Adder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Add/Adder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Adder(ctx, req.(*AdderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Add",
	HandlerType: (*AddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Adder",
			Handler:    _Add_Adder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add.proto",
}
